app/report/views.py
from flask import render_template, g, Blueprint, jsonify, current_app, redirect, url_for
from flask_login import login_required

# Module imports
from .models import CallTable
from .core import get_download, show_records, get_report, empty_frame, test_record_getter

bp = Blueprint(
    'report',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/report/static'
)


@bp.route('/fill', methods=['GET'])
def fill():
    test_record_getter()
    return redirect(url_for('.index'))


@bp.route('/view', methods=['GET', 'POST'])
@login_required
def index():
    return render_template(
        'report_template.html',
        title='Data Gallery',
        columns=list(CallTable.__table__.columns.keys()),
        iDisplayLength=current_app.config['ROWS_PER_PAGE'],
        page='view'
    )


@bp.route('/report', methods=['GET'])
@bp.route('/report/<string:report_type>', methods=['GET', 'POST'])
@login_required
def report(report_type='SLA'):
    return render_template(
        'report_template.html',
        title='{type} Report'.format(type=report_type.upper()),
        columns=['Client'] + current_app.config['sla_report_headers'],
        iDisplayLength=-1,
        page='report'
    )


@bp.route('/api', methods=['GET'])
def api():

    # Parser section
    g.parser.add_argument('start', type=int, location='args')
    g.parser.add_argument('draw', type=int, location='args')
    g.parser.add_argument('length', type=int, location='args')
    g.parser.add_argument('action', type=str, location='args')
    g.parser.add_argument('report_range', type=str, location='args')
    args = g.parser.parse_args()

    # Action stuff
    if args['action'] == 'report':
        # Celery worker will draw records
        print('getting report')
        frame, total = get_report(g.session, args)
    elif args['action'] == 'view':
        # Draw records
        print('getting records')
        frame, total = show_records(g.session, args)
    else:
        frame, total = empty_frame()

    if args['action'] == 'download':
        get_download()

    # Separate data into the format Ajax expects
    results = frame.to_dict(orient='split')

    return jsonify(
        draw=args['draw'],
        recordsTotal=total,
        recordsFiltered=total,
        data=results['data']
    )

app/user/views.py
from flask import render_template, flash, redirect, url_for, request, g, Blueprint
from flask_login import login_user, logout_user, login_required

from .core import new_user, existing_user, add_client, remove_client, delete_client
from app.core import get_redirect_target


bp = Blueprint(
    'user',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/user/static'
)


@bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():

    if not any((g.user, g.user.is_authenticated)):
        return redirect(
            url_for('index')
        )

    # Parser section
    g.parser.add_argument('client_name', type=str, location='form')
    g.parser.add_argument('client_id', type=str, location='form')
    g.parser.add_argument('full_service', type=bool, location='form')
    g.parser.add_argument('remove', type=str, location='form')
    g.parser.add_argument('delete', type=str, location='form')

    args = g.parser.parse_args()

    if request.method == 'POST' and args['remove']:

        user = remove_client(args['remove'])
        # Save change to session
        g.session.add(user)

    elif request.method == 'POST' and args['delete']:

        # Delete needs to be committed to be saved
        delete_client(g.session, args['delete'])

    elif request.method == 'POST':

        user = add_client(args['client_name'], args['client_id'], args['full_service'])
        # Save change to session
        g.session.add(user)

    return render_template(
        'settings_template.html',
        title='Settings',
        user=g.user
    )


@bp.route('/login', methods=['GET', 'POST'])
def login():

    if all((g.user, g.user.is_authenticated)):
        return redirect(
            url_for('index')
        )

    next_tgt = get_redirect_target()

    # Parser section
    g.parser.add_argument('user_name', type=str, location='form')
    g.parser.add_argument('password', type=str, location='form')
    g.parser.add_argument('remember_me', type=bool, location='form')
    args = g.parser.parse_args()

    if request.method == 'POST':

        user = existing_user(g.session, args)

        if not user:
            user = new_user(args)
            g.session.add(user)
            g.session.commit()
            flash('Successfully created login for', user.alias)

        if user.verify_password(args['password']):
            # User Login
            success = login_user(user, remember=args['remember_me'])
            flash('Login {s}.'.format(s='success!' if success else 'failed!'))

        return redirect(next_tgt)

    return render_template(
        'login_template.html',
        title='Sign In',
        next=next_tgt
    )


@bp.route("/logout", methods=['GET'])
@login_required
def logout():
    success = logout_user()
    flash('Logout {s}.'.format(s='success!' if success else 'failed!'))
    return redirect(url_for('index'))

app/templates/navigation/authenticated_user.html
<!-- Display authenticated user options-->
<div class="navbar-link navbar-text dropdown">
    Signed in as {{ g.user.email }}

    <button type="button" id="userButtons" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="caret"></span>
        <span class="sr-only">Toggle User Options</span>
    </button>

    <div class="dropdown-menu" aria-labelledby="userButtons">
        <!-- Dropdown menu links -->
        <a class="dropdown-item btn" href="{{ url_for('user.settings') }}">Settings</a>
        <a class="dropdown-item btn" href="{{ url_for('user.logout') }}">Logout</a>
    </div>
</div>

app/templates/navigation/header.html
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header navbar-link">
    <a class="navbar-brand" href="{{ url_for('index') }}">
                <img alt="mW Reporting" src="{{ url_for('static', filename='img/brand.ico') }}"
                     width="auto" height="100%">
            </a>
    <div class="navbar-text">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#base-navbar"
                aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
</div>

app/templates/navigation/navigation.html
<!-- Navigation bar for all base pages -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">   <!-- Maximum screen width -->

        <!-- Brand and toggle get grouped for better mobile display -->
        <p class="base-navbar">{% include 'navigation/header.html' %}</p>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <ul class="nav navbar-nav collapse navbar-collapse" id="base-navbar">

            <!-- Public contact information -->
            <li class="base-navbar">{% include 'navigation/public.html' %}</li>

            <!-- If search enabled display the search form -->
            {% if g.search_enabled %}
                <li class="base-navbar">{% include 'navigation/search.html' %}</li>
            {% endif %}

            <!-- Display login options -->
            {% if g.user.is_authenticated %}
                <li class="base-navbar">{% include 'navigation/authenticated_user.html' %}</li>
            {% else %}
                <li class="base-navbar">{% include 'navigation/public_user.html' %}</li>
            {% endif %}

        </ul>
    </div><!-- /.container-fluid -->
</nav>

app/templates/navigation/public.html
<!-- Public contact information  -->
<div class="navbar-link navbar-text dropdown">
    <a href="{{ url_for('report.index') }}">Reports</a>

    <button type="button" id="publicButtons" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="caret"></span>
        <span class="sr-only">Toggle Artist Page</span>
    </button>

    <ul class="dropdown-menu" aria-labelledby="publicButtons" role="menu">
        <!-- Dropdown menu links -->
        <li><a class="dropdown-item btn" href="#">My Report</a></li>
        <li><a class="dropdown-item btn" href="#">My Report</a></li>
        <li class="divider"></li>
        <li><a class="dropdown-item btn" href="#">Basic Report</a></li>
    </ul>
</div>

app/templates/navigation/public_user.html
<!-- Public user options -->
<form class="navbar-form navbar-text" method="GET" action="{{ url_for('user.login') }}">
    <div class="form-group">
        <button type="submit" class="btn btn-secondary">Login</button>
    </div>
</form>

app/templates/navigation/search.html
<!-- If search enabled display the search form-->
<form class="navbar-form navbar-text" method="POST" action="">
    <div class="form-group">
        <input title="Type search term here" type="text" placeholder="Subject, Author, etc..." name="search"/>
        <button type="submit" class="btn btn-secondary">Search</button>
    </div>
</form>