app/report/views.py
from flask import render_template, g, Blueprint, jsonify, current_app, redirect, url_for
from flask_login import login_required

# Module imports
from .models import CallTable
from .core import get_download, show_records, get_report, empty_frame, test_record_getter

bp = Blueprint(
    'report',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/report/static'
)


@bp.route('/fill', methods=['GET'])
def fill():
    test_record_getter()
    return redirect(url_for('.index'))


@bp.route('/view', methods=['GET', 'POST'])
@login_required
def index():
    return render_template(
        'report_template.html',
        title='Data Gallery',
        columns=list(CallTable.__table__.columns.keys()),
        iDisplayLength=current_app.config['ROWS_PER_PAGE'],
        page='view'
    )


@bp.route('/report', methods=['GET'])
@bp.route('/report/<string:report_type>', methods=['GET', 'POST'])
@login_required
def report(report_type='SLA'):
    return render_template(
        'report_template.html',
        title='{type} Report'.format(type=report_type.upper()),
        columns=['Client'] + current_app.config['sla_report_headers'],
        iDisplayLength=-1,
        page='report'
    )


@bp.route('/api', methods=['GET'])
def api():

    # Parser section
    g.parser.add_argument('start', type=int, location='args')
    g.parser.add_argument('draw', type=int, location='args')
    g.parser.add_argument('length', type=int, location='args')
    g.parser.add_argument('action', type=str, location='args')
    g.parser.add_argument('report_range', type=str, location='args')
    args = g.parser.parse_args()

    # Action stuff
    if args['action'] == 'report':
        # Celery worker will draw records
        print('getting report')
        frame, total = get_report(g.session, args)
    elif args['action'] == 'view':
        # Draw records
        print('getting records')
        frame, total = show_records(g.session, args)
    else:
        frame, total = empty_frame()

    if args['action'] == 'download':
        get_download()

    # Separate data into the format Ajax expects
    results = frame.to_dict(orient='split')

    return jsonify(
        draw=args['draw'],
        recordsTotal=total,
        recordsFiltered=total,
        data=results['data']
    )

app/report/templates/data_controls.html
<!-- Modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#frameModal">
    Query Settings
</button>
<div class="modal fade" id="frameModal" tabindex="-1" role="dialog" aria-labelledby="frameModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="frameModalLabel">Query Properties</h5>
                <p>Current query information...</p>
            </div>
            <div class="modal-body">
                <div class="input-group">
                    <input id="report_range" type="text" title="Select report dates..."
                           name="report_range" class="form-control">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar fa fa-calendar" aria-hidden="true">&nbsp;</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save_selection">Save</button>
                <button type="button" class="btn btn-primary" id="change_range">Update</button>
                <button type="button" class="btn btn-primary" id="run_range">Run</button>
            </div>
        </div>
    </div>
</div>

app/report/templates/query_properties.html
<!-- Modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#frameModal">
    Query Settings
</button>
<div class="modal fade" id="frameModal" tabindex="-1" role="dialog" aria-labelledby="frameModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="frameModalLabel">Query Properties</h5>
                <p>Current query information...</p>
            </div>
            <div class="modal-body">
                <div class="input-group">
                    <input id="report_range" type="text" title="Select report dates..." name="report_range"
                           class="form-control" style="cursor: pointer;">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar fa fa-calendar" aria-hidden="true">&nbsp;</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save_selection">Save</button>
                <button type="button" class="btn btn-primary" id="change_range">Update</button>
                <button type="button" class="btn btn-primary" id="run_range">Run</button>
            </div>
        </div>
    </div>
</div>

app/report/templates/query_properties_partial.html
<!-- Modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#frameModal">
    Query Settings
</button>
<div class="modal fade" id="frameModal" tabindex="-1" role="dialog" aria-labelledby="frameModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="frameModalLabel">Query Properties</h5>
                <p>Current query information...</p>
            </div>
            <div class="modal-body">
                <div class="input-group">
                    <input id="report_range" type="text" title="Select report dates..." name="report_range"
                           class="form-control" style="cursor: pointer;">
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar fa fa-calendar" aria-hidden="true">&nbsp;</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save_selection">Save</button>
                <button type="button" class="btn btn-primary" id="change_range">Update</button>
                <button type="button" class="btn btn-primary" id="run_range">Run</button>
            </div>
        </div>
    </div>
</div>

app/report/templates/report.html
<!-- Index page for data in report module -->
{% extends 'base.html' %}

{% block extracss %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
    {#    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">#}
    {#    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.2/css/fixedHeader.bootstrap.min.css">#}
    {#    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css">#}


    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('report.static', filename='report.css') }}">
{% endblock %}

{% block content %}
    <div class="container-fluid padded">
        <div class="container-fluid text-centered padded">
            <!-- Button trigger modal -->
            {% include 'query_properties.html' %}
            <table id="displayTable" class="display" cellspacing="0" width="100%">
                <!-- Configure the headers for the ajax call-->
                <thead><tr>{% for column in columns %}<th>{{ column }}</th>{% endfor %}</tr></thead>
                <tfoot><tr>{% for column in columns %}<th>{{ column }}</th>{% endfor %}</tr></tfoot>
            </table>
        </div>
    </div>  <!-- /.container-fluid -->
{% endblock %}

{% block extrajs %}
    {{ super() }}
    <!-- Include Date Range Picker -->
    <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>

    <!-- Include dataTable -->
    <script type="text/javascript" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

    {#    <script type="text/javascript" src="//cdn.datatables.net/fixedheader/3.1.2/js/dataTables.fixedHeader.min.js"></script>#}


    <!-- Submit form for DataTable /w DataTable -->
    {#    <script type="text/javascript" src="{{ url_for('report.static', filename='submit_form.js') }}"></script>#}

    <!-- Datepicker, Modal and DataTable JS -->
    <script type="text/javascript">
        $(document).ready(function () {
            let page_type;

            function buildAjaxData() {
                let settings = $("#displayTable").dataTable().fnSettings();
                console.log(settings);

                let obj = {
                    //default params
                    "draw": settings.iDraw,
                    "start": settings._iDisplayStart,
                    "length": settings._iDisplayLength,
                    "columns": "",
                    "order": "",

                    "type": page_type,
                    "report_range": $('input[name="report_range"]').val()
                };

                //building the columns
                let col = []; // array

                for(let index in settings.aoColumns){
                    let data = settings.aoColumns[index];
                    col.push(data.sName);

                }

                let ord = {
                    "column": settings.aLastSort[0].col,
                    "dir": settings.aLastSort[0].dir
                };

                //assigning
                obj.columns = col;
                obj.order = ord;

                return obj;


            }
            let start = moment().subtract(1, 'days');
            let end = moment();

            /* Set displayed range in the datepicker */
            function cb(start, end) {
                $('#report_range').find('span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            }

            $('input#report_range').daterangepicker({
                startDate: start,
                endDate: end,
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                },
                useCurrent: true
            }, cb);

            cb(start, end); /* Init the report_range */

            let ajaxUrl = "{{ url_for('report.data') }}";

            let table = $('#displayTable').DataTable( {
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": ajaxUrl,
                    "data": buildAjaxData
                },
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
            } );

            $('button#change_range').bind('click', function () {
                $('#frameModal').modal('hide');
                page_type = "data";
                table.ajax.reload();
            });
            $('button#save_selection').bind('click', function () {
                $('#frameModal').modal('hide');
                table.ajax.reload();
            });
            $('button#run_range').bind('click', function () {
                $('#frameModal').modal('hide');
                page_type = "report";
                table.ajax.reload();
            });
        });
    </script>
{% endblock %}

app/report/templates/report_template.html
<!-- Index page for data in report module -->
{% extends 'base.html' %}

{% block extracss %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('report.static', filename='report.css') }}">
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css"/>
{% endblock %}

{% block content %}
    <div class="container-fluid padded">
        <div class="row padded">
            <!-- Button trigger modal -->
            {% include 'data_controls.html' %}
        </div>

        <table id="displayTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <!-- Configure the headers for the ajax call-->
            <thead>
            <tr>{% for column in columns %}
                <th>{{ column }}</th>{% endfor %}</tr>
            </thead>
            <tfoot>
            <tr>{% for column in columns %}
                <th>{{ column }}</th>{% endfor %}</tr>
            </tfoot>
        </table>
    </div>  <!-- /.container-fluid -->
{% endblock %}

{% block extrajs %}
    {{ super() }}

    <!-- Get moment JS for relative timestamps -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment-with-locales.min.js"></script>

    <!-- Include Date Range Picker -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>

    <!-- Include dataTable -->
    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

    <!-- Datepicker, Modal and DataTable JS -->
    <script type="text/javascript">
        $(document).ready(function () {
            $.getScript("{{ url_for('report.static', filename='js/modal.js') }}", function () {
                /* Init the report_range */
                cb(start, end);
            });

            $.getScript("{{ url_for('report.static', filename='js/ajax_fn.js') }}", function () {
                /* Super hack */
                sessionStorage.action = '{{ page }}';

                let table = $('#displayTable').DataTable({
                    "processing": true,
                    "serverSide": true,
                    "ajax": {
                        "url": "{{ url_for('report.api') }}",
                        "data": buildAjaxData
                    },
                    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                    "iDisplayLength": {{ iDisplayLength }}
                });
                function page_api(event) {
                    $('#frameModal').modal('hide');
                    sessionStorage.action = event.data.action;
                    table.ajax.reload();
                }

                $('button#change_range').on('click', {
                    action: "view"
                }, page_api);

                $('button#save_selection').on('click', {
                    action: "download"
                }, page_api);

                $('button#run_range').on('click', {
                    action: "report"
                }, page_api);
            });
        });
    </script>
{% endblock %}